### PR TITLE
swapped to v5.0.0 font file

### PR DESCRIPTION
**Pull request by JacksonLaw**
changed the file over -- It looks like all the fonts worked. 
I used https://github.com/FontCustom/fontcustom to convert the svg files ( https://github.com/ionic-team/ionicons/tree/master/src/svg ) to a .tff file.

### CODE REVIEW

**Comment by arniu** [comment]
Nick catch!

According to [ionicons v5 changelog](https://github.com/ionic-team/ionicons/blob/master/CHANGELOG.md#500-2020-02-06), many icons have changed their names. As a  result, the generated file `glyph/map.json` should be updated too.

Can you give a try, with a script ?

**Comment by arniu** [comment]
NPM has a [svg2ttf](https://www.npmjs.com/package/svg2ttf).

**Comment by JacksonLaw** [comment]
Okay I've modified your generate.js file and have subsequently pushed a new map.json file.
Left the modified file off of the commit as I'm unsure how you would usually run this.

**Comment by arniu** [comment]
Thanks very much!

**Pull request merged**
